### ISSUE TITLE
Additional requirements

### ISSUE THREAD

**Issue by boostvolt** [dreamscore-oss/platform#6]
Further functional and, above all, non-functional requirements (boundary conditions and quality requirements) are specified here. In addition, important rules of the problem area (e.g. business or game rules) and other important information (e.g. further specifications and boundary conditions for the development of the application) are listed.

Get inspiration from the Kickbase points table: https://en.kickbase.com/points-table

**Comment by bossarom** [comment]
Subtasks:

- Functional Requirements
- Non-Functional Requirements
- Rules
- Pointing System For Players
